{% set name = "certbot" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/certbot-{{ version }}.tar.gz
  sha256: 2939a248def1a8bce661f8d92f9add975108741d7d96fcbfff2936031e72930c

build:
  noarch: python
  entry_points:
    - certbot = certbot.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - acme >={{ version }}
    - configargparse >=1.5.3
    - configobj >=5.0.6
    - cryptography >=3.2.1
    - distro >=1.0.1
    - josepy >=1.13.0,<2
    - parsedatetime >=2.4
    - pyrfc3339
    - pytz >=2019.3
    - pywin32-on-windows
    - setuptools >=41.6.0
    - importlib-metadata >=4.6
  run_constrained:
    - pywin32 >=300

test:
  imports:
    - certbot
    - certbot._internal
  commands:
    - pip check
    - certbot --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME client
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
