{% set name = "certbot" %}
{% set version = "1.31.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-{{ version }}.tar.gz
  sha256: 29af531d33aaa87c8104864cd31ac2af541f0ec973a7252d7f7f5b15e10479db

build:
  number: 1
  skip: true  # [py<37]
  entry_points:
    - certbot = certbot.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - acme >={{ version }}
    - configargparse >=0.9.3
    - configobj >=5.0.6
    - cryptography >=2.5.0
    - distro >=1.0.1
    - josepy >=1.13.0
    - parsedatetime >=2.4
    - pyrfc3339
    - python
    - pytz >=2019.3
    - pywin32 >=300  # [win]
    - setuptools >=41.6.0
    - zope.component
    - zope.interface

test:
  imports:
    - certbot
    - certbot._internal
  commands:
    - pip check
    - certbot --help
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME client
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
