schema_version: 1

context:
  version: "5.8.0"

package:
  name: certbot
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/certbot/certbot-${{ version }}.tar.gz
  sha256: a4a2c7b0459bb626b3791ef07b6df26bbb222d2324783ba3e60f76c0933eec87

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - certbot = certbot.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - configargparse >=1.5.3
    - configobj >=5.0.6
    - cryptography >=43.0.0
    - distro >=1.0.1
    - josepy >=2.0.0
    - parsedatetime >=2.6
    - pyrfc3339
    - pywin32-on-windows
  run_constraints:
    - pywin32 >=300

tests:
  - python:
      imports:
        - certbot
        - certbot._internal
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - certbot --help

about:
  summary: ACME client
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/letsencrypt/letsencrypt

extra:
  recipe-maintainers:
    - nehaljwani
    - pavelzw
